import { LexiconDict } from './index'

export const commonLexicon: LexiconDict = {
  ru: {
    'error.http': 'Ошибка HTTP: {{status}}',
    'error.noResponseBody': 'Нет тела ответа',
    'error.inAgent': 'Ошибка в {{nodeName}}',
    'error.unknown': 'Неизвестная ошибка',
    'error.somethingWentWrong':
      'Извините, что-то пошло не так. Попробуйте снова.',
    'chat.title': 'Conceptica AI',
    'chat.subtitle': '',
    'chat.status': 'Онлайн',
    read: 'Читать',
  },
  en: {
    'error.http': 'HTTP Error: {{status}}',
    'error.noResponseBody': 'No response body',
    'error.inAgent': 'Error in {{nodeName}}',
    'error.unknown': 'Unknown error',
    'error.somethingWentWrong':
      'Sorry, something went wrong. Please try again.',
    'chat.title': 'Conceptica AI',
    'chat.subtitle': '',
    'chat.status': 'Online',
    read: 'Read',
  },
  vi: {
    'error.http': 'Lỗi HTTP: {{status}}',
    'error.noResponseBody': 'Không có nội dung phản hồi',
    'error.inAgent': 'Lỗi trong {{nodeName}}',
    'error.unknown': 'Lỗi không xác định',
    'error.somethingWentWrong': 'Xin lỗi, đã xảy ra lỗi. Vui lòng thử lại.',
    'chat.title': 'Conceptica AI',
    'chat.subtitle': '',
    'chat.status': 'Trực tuyến',
    read: 'Đọc',
  },
  es: {
    'error.http': 'Error HTTP: {{status}}',
    'error.noResponseBody': 'Sinon cuerpo de respuesta',
    'error.inAgent': 'Error en {{nodeName}}',
    'error.unknown': 'Error desconocido',
    'error.somethingWentWrong':
      'Lo sentimos, algo salió mal. Inténtelo de nuevo.',
    'chat.title': 'Conceptica AI',
    'chat.subtitle': '',
    'chat.status': 'En línea',
    read: 'Leer',
  },
  zh: {
    'error.http': 'HTTP 错误：{{status}}',
    'error.noResponseBody': '无响应正文',
    'error.inAgent': '{{nodeName}} 中的错误',
    'error.unknown': '未知错误',
    'error.somethingWentWrong': '抱歉，出了点问题。请重试。',
    'chat.title': 'Conceptica AI',
    'chat.subtitle': '',
    'chat.status': '在线',
    read: '阅读',
  },
  pt: {
    'error.http': 'Erro HTTP: {{status}}',
    'error.noResponseBody': 'Sem corpo de resposta',
    'error.inAgent': 'Erro em {{nodeName}}',
    'error.unknown': 'Erro desconhecido',
    'error.somethingWentWrong': 'Desculpe, algo deu errado. Tente novamente.',
    'chat.title': 'Conceptica AI',
    'chat.subtitle': '',
    'chat.status': 'Online',
    read: 'Ler',
  },
  hi: {
    'error.http': 'HTTP त्रुटि: {{status}}',
    'error.noResponseBody': 'कोई प्रतिक्रिया निकाय नहीं',
    'error.inAgent': '{{nodeName}} में त्रुटि',
    'error.unknown': 'अज्ञात त्रुटि',
    'error.somethingWentWrong':
      'खेद है, कुछ गलत हो गया। कृपया पुनः प्रयास करें।',
    'chat.title': 'Conceptica AI',
    'chat.subtitle': '',
    'chat.status': 'ऑनलाइन',
    read: 'पढ़ना',
  },
  fr: {
    'error.http': 'Erreur HTTP : {{status}}',
    'error.noResponseBody': 'Aucun corps de réponse',
    'error.inAgent': 'Erreur dans {{nodeName}}',
    'error.unknown': 'Erreur inconnue',
    'error.somethingWentWrong':
      'Désolé, une erreur est survenue. Veuillez réessayer.',
    'chat.title': 'Conceptica AI',
    'chat.subtitle': '',
    'chat.status': 'En ligne',
    read: 'Lire',
  },
  bn: {
    'error.http': 'HTTP ত্রুটি: {{status}}',
    'error.noResponseBody': 'কোনো প্রতিক্রিয়া বডি নেই',
    'error.inAgent': '{{nodeName}} এ ত্রুটি',
    'error.unknown': 'অজানা ত্রুটি',
    'error.somethingWentWrong': 'দুঃখিত, কিছু ভুল হয়েছে। আবার চেষ্টা করুন।',
    'chat.title': 'Conceptica AI',
    'chat.subtitle': '',
    'chat.status': 'অনলাইন',
    read: 'পড়া',
  },
  de: {
    'error.http': 'HTTP-Fehler: {{status}}',
    'error.noResponseBody': 'Kein Antworttext',
    'error.inAgent': 'Fehler in {{nodeName}}',
    'error.unknown': 'Unbekannter Fehler',
    'error.somethingWentWrong':
      'Entschuldigung, etwas ist schiefgelaufen. Bitte versuchen Sie es erneut.',
    'chat.title': 'Conceptica AI',
    'chat.subtitle': '',
    'chat.status': 'Online',
    read: 'Lesen',
  },
  ja: {
    'error.http': 'HTTPエラー: {{status}}',
    'error.noResponseBody': 'レスポンス本文がありません',
    'error.inAgent': '{{nodeName}}でエラーが発生しました',
    'error.unknown': '不明なエラー',
    'error.somethingWentWrong':
      '申し訳ありませんが、エラーが発生しました。もう一度お試しください。',
    'chat.title': 'Conceptica AI',
    'chat.subtitle': '',
    'chat.status': 'オンライン',
    read: '読む',
  },
  tr: {
    'error.http': 'HTTP Hatası: {{status}}',
    'error.noResponseBody': 'Yanıt gövdesi yok',
    'error.inAgent': '{{nodeName}} içinde hata',
    'error.unknown': 'Bilinmeyen hata',
    'error.somethingWentWrong':
      'Üzgünüz, bir hata oluştu. Lütfen tekrar deneyin.',
    'chat.title': 'Conceptica AI',
    'chat.subtitle': '',
    'chat.status': 'Çevrimiçi',
    read: 'Okumak',
  },
  ko: {
    'error.http': 'HTTP 오류: {{status}}',
    'error.noResponseBody': '응답 본문 없음',
    'error.inAgent': '{{nodeName}} 오류',
    'error.unknown': '알 수 없는 오류',
    'error.somethingWentWrong':
      '죄송합니다. 문제가 발생했습니다. 다시 시도해 주세요.',
    'chat.title': 'Conceptica AI',
    'chat.subtitle': '',
    'chat.status': '온라인',
    read: '읽기',
  },
  th: {
    'error.http': 'ข้อผิดพลาด HTTP: {{status}}',
    'error.noResponseBody': 'ไม่มีเนื้อหาการตอบสนอง',
    'error.inAgent': 'ข้อผิดพลาดใน {{nodeName}}',
    'error.unknown': 'ข้อผิดพลาดที่ไม่รู้จัก',
    'error.somethingWentWrong': 'ขออภัย มีข้อผิดพลาดเกิดขึ้น โปรดลองอีกครั้ง',
    'chat.title': 'Conceptica AI',
    'chat.subtitle': '',
    'chat.status': 'ออนไลน์',
    read: 'อ่าน',
  },
  sw: {
    'error.http': 'Hitilafu la HTTP: {{status}}',
    'error.noResponseBody': 'Hakuna mwili wa majibu',
    'error.inAgent': 'Kosa katika {{nodeName}}',
    'error.unknown': 'Kosa lisilojulikana',
    'error.somethingWentWrong':
      'Samahani, kuna hitilafu. Tafadhali jaribu tena.',
    'chat.title': 'Conceptica AI',
    'chat.subtitle': '',
    'chat.status': 'Mtandaoni',
    read: 'Kusoma',
  },
  it: {
    'error.http': 'Errore HTTP: {{status}}',
    'error.noResponseBody': 'Nessun corpo di risposta',
    'error.inAgent': 'Errore in {{nodeName}}',
    'error.unknown': 'Errore sconosciuto',
    'error.somethingWentWrong':
      'Spiacenti, si è verificato un errore. Riprova.',
    'chat.title': 'Conceptica AI',
    'chat.subtitle': '',
    'chat.status': 'Online',
    read: 'Leggere',
  },
  pl: {
    'error.http': 'Błąd HTTP: {{status}}',
    'error.noResponseBody': 'Brak treści odpowiedzi',
    'error.inAgent': 'Błąd w {{nodeName}}',
    'error.unknown': 'Nieznany błąd',
    'error.somethingWentWrong':
      'Przepraszamy, coś poszło nie tak. Spróbuj ponownie.',
    'chat.title': 'Conceptica AI',
    'chat.subtitle': '',
    'chat.status': 'Online',
    read: 'Czytać',
  },
  fil: {
    'error.http': 'Error sa HTTP: {{status}}',
    'error.noResponseBody': 'Walang katawan ng tugon',
    'error.inAgent': 'Error sa {{nodeName}}',
    'error.unknown': 'Hindi kilalang error',
    'error.somethingWentWrong':
      'Paumanhin, may nangyaring error. Mangyaring subukan muli.',
    'chat.title': 'Conceptica AI',
    'chat.subtitle': '',
    'chat.status': 'Online',
    read: 'Magbasa',
  },
  ms: {
    'error.http': 'Ralat HTTP: {{status}}',
    'error.noResponseBody': 'Tiada badan respons',
    'error.inAgent': 'Ralat dalam {{nodeName}}',
    'error.unknown': 'Ralat tidak diketahui',
    'error.somethingWentWrong': 'Maaf, berlaku ralat. Sila cuba lagi.',
    'chat.title': 'Conceptica AI',
    'chat.subtitle': '',
    'chat.status': 'Dalam talian',
    read: 'Membaca',
  },
}
